const express = require("express");
const crypto = require("crypto");
const { Inngest } = require("inngest");
const { serve } = require("inngest/express");

process.env.INNGEST_DEV = process.env.INNGEST_DEV || "1";

const app = express();
const PORT = process.env.PORT || 3001;

app.use(express.json());

// In-memory store generated by AI
const reportsStore = {};

// Inngest Client
const inngest = new Inngest({ id: "ai-report-service", isDev: true });

// Function: say-hello
const sayHelloFn = inngest.createFunction(
  { id: "ai-say-hello", triggers: [{ event: "test/hello" }] },
  async ({ step }) => {
    await step.sleep("wait-5-seconds", "5s");
    return { message: "Hello from the background!" };
  }
);

// Function: make-report
const makeReportFn = inngest.createFunction(
  { id: "ai-make-report", triggers: [{ event: "report/requested" }], retries: 2 },
  async ({ event, step }) => {
    const { id, topic } = event.data;

    await step.sleep("simulate-generation", "8s");

    return await step.run("generate-report-data", async () => {
      if (topic === "fail") {
        throw new Error("The report oven is broken!");
      }

      const generated = {
        id,
        topic,
        status: "done",
        data: `AI Report generated for: ${topic}`,
        completedAt: new Date().toISOString(),
      };
      reportsStore[id] = generated;
      return generated;
    });
  }
);

// Function: heartbeat cron
const cronHeartbeat = inngest.createFunction(
  { id: "ai-heartbeat", triggers: [{ cron: "* * * * *" }] },
  async ({ step }) => {
    return await step.run("summarize", () => {
      const items = Object.values(reportsStore);
      const pendingCount = items.filter((r) => r.status === "pending").length;
      const doneCount = items.filter((r) => r.status === "done").length;
      const failedCount = items.filter((r) => r.status === "failed").length;

      const logMsg = `[AI Cron] Pending: ${pendingCount}, Done: ${doneCount}, Failed: ${failedCount}`;
      console.log(logMsg);
      return { logMsg, total: items.length };
    });
  }
);

// Health check
app.get("/health", (req, res) => {
  res.json({ status: "ok" });
});

// Create report endpoint
app.post("/reports", async (req, res) => {
  const { topic } = req.body;
  if (!topic || typeof topic !== "string" || !topic.trim()) {
    return res.status(400).json({ error: "Topic is required" });
  }

  const id = crypto.randomUUID();
  reportsStore[id] = {
    id,
    topic,
    status: "pending",
    createdAt: new Date().toISOString(),
  };

  await inngest.send({
    name: "report/requested",
    data: { id, topic },
  });

  res.status(202).json({ id, status: "pending" });
});

// Status check endpoint
app.get("/reports/:id", (req, res) => {
  const report = reportsStore[req.params.id];
  if (!report) {
    return res.status(404).json({ error: "Report not found" });
  }
  res.json(report);
});

// Inngest endpoint
app.use(
  "/api/inngest",
  serve({
    client: inngest,
    functions: [sayHelloFn, makeReportFn, cronHeartbeat],
  })
);

app.listen(PORT, () => {
  console.log(`AI-Version Server running on port ${PORT}`);
});
